### PR TITLE
Migrating Docs from Wiki to Github

### PR DESCRIPTION
**Pull request by sladyn98**

### CODE REVIEW

**Comment by timja** [comment]
cc @amuniz

**Review by amuniz — APPROVED** [review]

**Comment by timja** [comment]
merge and release? 😄

**Comment by amuniz** [comment]
I'm not really maintaining this plugin, it happens that it was created by me :) I can merge and release blindly though.

**Comment by amuniz** [comment]
BTW, does this need to be released? It's just docs

**Comment by timja** [comment]
ugh, onesec

**Pull request merged**
