### PR TITLE
Export "newerBuild" so that BO REST can use it

### PR DESCRIPTION
**Pull request by i386**
@amuniz very quick one to make the `CancelledCause` serialize better via Blue Ocean REST API.

Related to https://issues.jenkins-ci.org/browse/JENKINS-40871

### CODE REVIEW

**Comment by i386** [comment]
@jglick serialising the run would be bad for Blue Ocean as that object could be rather large and isn't in the format our client would understand, so I've opted to go with the `int` option as you have suggested.

I've also taken the liberty to clear up some messiness where the `CancelledCause` is constructed on cancel in the `MilestoneStepExecution`.

**Comment by jglick** [comment]
> serialising the run would be bad for Blue Ocean as that object could be rather large

That is why you select only the desired fields, using for example `tree`.

**Comment by adelcast** [comment]
@jglick any status update on this PR? After Jenkins World, I added some notes on the original PR that prompted this change: https://issues.jenkins-ci.org/browse/JENKINS-40871. Seems like once this gets in, we can start working on the UI side. I am not a front-end dev, but can certainly take a stab at it, as I think it would be super cool to have this "collapse" pipeline view on BO. If there is anything else I can help with to get this going, please let me know.

**Comment by jglick** [comment]
> any status update on this PR?

Ask the submitter. My last recommendation was to instead add `@Exported` to `getNewerBuild`.

**Comment by adelcast** [comment]
ah, you are right, I though the ball was on your court but is not. @i386 were you planning on following up on this PR? let me know if I can help from my end

**Comment by i386** [comment]
I am not working on this one anymore @adelcast - if you want to take over from here you can file a new PR :)

**Pull request closed without merging**
