### PR TITLE
[JENKINS-43353] Demo of aborting any running build(s) when we start a new one

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-43353](https://issues.jenkins-ci.org/browse/JENKINS-43353)

Test case demonstrates desired behavior, along with a crude workaround based on the current step.

@reviewbybees

### CODE REVIEW

**Comment by amuniz** [comment]
To be clear, adding a new test is always welcome and I would approve this PR, but I think the described workaround is not valid in a commonly used real world example.

**Comment by jglick** [comment]
If using this mode, I see no reason to have any other `milestone`s in the build: you will only have one build running at a time (except very briefly at the start of a new build).

**Comment by recampbell** [comment]
@reviewbybees  done

**Comment by jglick** [comment]
Testing rebuild (INFRA-1333)…

**Comment by abayer** [comment]
I don't have merge rights right - I'll open a PR to get that, but for now, @amuniz?

**Comment by jglick** [comment]
Version of [WAR on caching mirror](https://repo.azure.jenkins.io/public/org/jenkins-ci/main/jenkins-war/1.642.3/jenkins-war-1.642.3-war-for-test.jar) seems to have been corrupt, so may as well update the parent so we do not need this anyway.

**Comment by jglick** [comment]
> I am really confused what this is actually supposed to be testing -- the proposed workaround itself?

See the PR description. This demonstrates the desired behavior, and proves that it can be worked around with a trick.

> prefer to have a PR including the proposed 'eager' feature instead

Well sure, that would be great, but I think our general stance is that a PR which only adds a test for a desired feature or fix is better than nothing at all, since it at least provides a starting point for someone who _does_ have time and desire to work on the feature.

**Comment by bertjwregeer** [comment]
Inefficient... but for those developers at $WORK that like to git commit && push and then a minute later do another commit && push this work-around does wonders in keeping our build queues down.

**Pull request merged**
